#############################################################################
# Makefile for building: qt_papers
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Apr 12 20:22:45 2011
# Project:  qt_papers.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile qt_papers.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Werror -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Collection.cpp \
		Entry.cpp \
		EntryDialog.cpp \
		Importer.cpp \
		ImporterDialog.cpp \
		Library.cpp \
		LibraryDialog.cpp \
		LibraryList.cpp \
		Paper.cpp \
		PaperDialog.cpp \
		PaperList.cpp \
		PrefDialog.cpp \
		qt_papers.cpp \
		RssWidget.cpp moc_Collection.cpp \
		moc_EntryDialog.cpp \
		moc_ImporterDialog.cpp \
		moc_LibraryDialog.cpp \
		moc_LibraryList.cpp \
		moc_PaperList.cpp \
		moc_PrefDialog.cpp \
		moc_RssWidget.cpp \
		qrc_qt_papers.cpp
OBJECTS       = Collection.o \
		Entry.o \
		EntryDialog.o \
		Importer.o \
		ImporterDialog.o \
		Library.o \
		LibraryDialog.o \
		LibraryList.o \
		Paper.o \
		PaperDialog.o \
		PaperList.o \
		PrefDialog.o \
		qt_papers.o \
		RssWidget.o \
		moc_Collection.o \
		moc_EntryDialog.o \
		moc_ImporterDialog.o \
		moc_LibraryDialog.o \
		moc_LibraryList.o \
		moc_PaperList.o \
		moc_PrefDialog.o \
		moc_RssWidget.o \
		qrc_qt_papers.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qt_papers.pro
QMAKE_TARGET  = qt_papers
DESTDIR       = 
TARGET        = qt_papers

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt_papers.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile qt_papers.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile qt_papers.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qt_papers1.0.0 || $(MKDIR) .tmp/qt_papers1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qt_papers1.0.0/ && $(COPY_FILE) --parents Collection.h Entry.h EntryDialog.h Importer.h ImporterDialog.h Library.h LibraryDialog.h LibraryList.h Paper.h PaperDialog.h PaperList.h PrefDialog.h RssWidget.h .tmp/qt_papers1.0.0/ && $(COPY_FILE) --parents qt_papers.qrc .tmp/qt_papers1.0.0/ && $(COPY_FILE) --parents Collection.cpp Entry.cpp EntryDialog.cpp Importer.cpp ImporterDialog.cpp Library.cpp LibraryDialog.cpp LibraryList.cpp Paper.cpp PaperDialog.cpp PaperList.cpp PrefDialog.cpp qt_papers.cpp RssWidget.cpp .tmp/qt_papers1.0.0/ && (cd `dirname .tmp/qt_papers1.0.0` && $(TAR) qt_papers1.0.0.tar qt_papers1.0.0 && $(COMPRESS) qt_papers1.0.0.tar) && $(MOVE) `dirname .tmp/qt_papers1.0.0`/qt_papers1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qt_papers1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_Collection.cpp moc_EntryDialog.cpp moc_ImporterDialog.cpp moc_LibraryDialog.cpp moc_LibraryList.cpp moc_PaperList.cpp moc_PrefDialog.cpp moc_RssWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Collection.cpp moc_EntryDialog.cpp moc_ImporterDialog.cpp moc_LibraryDialog.cpp moc_LibraryList.cpp moc_PaperList.cpp moc_PrefDialog.cpp moc_RssWidget.cpp
moc_Collection.cpp: Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		Collection.h \
		PaperList.h \
		RssWidget.h \
		Collection.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Collection.h -o moc_Collection.cpp

moc_EntryDialog.cpp: Library.h \
		Paper.h \
		Entry.h \
		EntryDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) EntryDialog.h -o moc_EntryDialog.cpp

moc_ImporterDialog.cpp: ImporterDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ImporterDialog.h -o moc_ImporterDialog.cpp

moc_LibraryDialog.cpp: Library.h \
		Paper.h \
		Entry.h \
		LibraryDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LibraryDialog.h -o moc_LibraryDialog.cpp

moc_LibraryList.cpp: Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		PaperList.h \
		RssWidget.h \
		LibraryList.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LibraryList.h -o moc_LibraryList.cpp

moc_PaperList.cpp: Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		PaperList.h \
		RssWidget.h \
		PaperList.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) PaperList.h -o moc_PaperList.cpp

moc_PrefDialog.cpp: PrefDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) PrefDialog.h -o moc_PrefDialog.cpp

moc_RssWidget.cpp: RssWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) RssWidget.h -o moc_RssWidget.cpp

compiler_rcc_make_all: qrc_qt_papers.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qt_papers.cpp
qrc_qt_papers.cpp: qt_papers.qrc \
		images/new.png \
		images/find.png \
		images/about.png \
		images/back.png \
		images/exit.png \
		images/forward.png \
		images/scan.png \
		images/pref.png \
		images/save.png \
		images/clear.png \
		images/edit.png \
		images/remove.png \
		images/document2.png \
		images/import.png \
		images/open.png \
		images/libopen.png \
		images/libremove.png
	/usr/bin/rcc -name qt_papers qt_papers.qrc -o qrc_qt_papers.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

Collection.o: Collection.cpp Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		PaperList.h \
		RssWidget.h \
		PrefDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Collection.o Collection.cpp

Entry.o: Entry.cpp Entry.h \
		EntryDialog.h \
		Library.h \
		Paper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Entry.o Entry.cpp

EntryDialog.o: EntryDialog.cpp EntryDialog.h \
		Library.h \
		Paper.h \
		Entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EntryDialog.o EntryDialog.cpp

Importer.o: Importer.cpp Importer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Importer.o Importer.cpp

ImporterDialog.o: ImporterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImporterDialog.o ImporterDialog.cpp

Library.o: Library.cpp Library.h \
		Paper.h \
		Entry.h \
		LibraryDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Library.o Library.cpp

LibraryDialog.o: LibraryDialog.cpp LibraryDialog.h \
		Library.h \
		Paper.h \
		Entry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibraryDialog.o LibraryDialog.cpp

LibraryList.o: LibraryList.cpp LibraryList.h \
		Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		PaperList.h \
		RssWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LibraryList.o LibraryList.cpp

Paper.o: Paper.cpp Paper.h \
		Entry.h \
		PaperDialog.h \
		Library.h \
		EntryDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Paper.o Paper.cpp

PaperDialog.o: PaperDialog.cpp PaperDialog.h \
		Library.h \
		Paper.h \
		Entry.h \
		EntryDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PaperDialog.o PaperDialog.cpp

PaperList.o: PaperList.cpp PaperList.h \
		Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		RssWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PaperList.o PaperList.cpp

PrefDialog.o: PrefDialog.cpp PrefDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrefDialog.o PrefDialog.cpp

qt_papers.o: qt_papers.cpp Collection.h \
		Library.h \
		Paper.h \
		Entry.h \
		LibraryList.h \
		PaperList.h \
		RssWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qt_papers.o qt_papers.cpp

RssWidget.o: RssWidget.cpp RssWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RssWidget.o RssWidget.cpp

moc_Collection.o: moc_Collection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Collection.o moc_Collection.cpp

moc_EntryDialog.o: moc_EntryDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EntryDialog.o moc_EntryDialog.cpp

moc_ImporterDialog.o: moc_ImporterDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImporterDialog.o moc_ImporterDialog.cpp

moc_LibraryDialog.o: moc_LibraryDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibraryDialog.o moc_LibraryDialog.cpp

moc_LibraryList.o: moc_LibraryList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LibraryList.o moc_LibraryList.cpp

moc_PaperList.o: moc_PaperList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PaperList.o moc_PaperList.cpp

moc_PrefDialog.o: moc_PrefDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PrefDialog.o moc_PrefDialog.cpp

moc_RssWidget.o: moc_RssWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RssWidget.o moc_RssWidget.cpp

qrc_qt_papers.o: qrc_qt_papers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qt_papers.o qrc_qt_papers.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

